services:
  db:
    image: pgvector/pgvector:pg16 
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=studyHubAI
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=khang562563
    ports:
      - "5431:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "85:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin123@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=khang563562
    restart: unless-stopped